export const mockEvents = [
  {
    id: 1,
    title: 'Douala Tech Summit',
    category: 'Technology',
    city: 'Douala',
    region: 'Littoral',
    venue: 'Bonanjo Conference Hall',
    startDate: '2026-08-15T08:00:00',
    price: 0,
    organizer: 'Cameroon Tech Network',
    popularity: 95,
    views: 2400,
    registrations: 430,
    description: 'A technology conference for developers, founders, students, and business leaders.',
  },
  {
    id: 2,
    title: 'Yaoundé Business Forum',
    category: 'Business',
    city: 'Yaoundé',
    region: 'Centre',
    venue: 'Hilton Yaoundé',
    startDate: '2026-09-02T09:00:00',
    price: 10000,
    organizer: 'Enterprise Cameroon',
    popularity: 88,
    views: 1800,
    registrations: 250,
    description: 'Networking and investment opportunities for entrepreneurs and professionals.',
  },
  {
    id: 3,
    title: 'Limbe Music Festival',
    category: 'Music',
    city: 'Limbe',
    region: 'South-West',
    venue: 'Limbe Beach',
    startDate: '2026-10-10T18:00:00',
    price: 5000,
    organizer: 'Culture Events CM',
    popularity: 92,
    views: 3100,
    registrations: 900,
    description: 'Live music, culture, food, and entertainment by the beach.',
  },
  {
    id: 4,
    title: 'Buea Career & Education Workshop',
    category: 'Education',
    city: 'Buea',
    region: 'South-West',
    venue: 'University of Buea',
    startDate: '2026-07-20T10:00:00',
    price: 0,
    organizer: 'Youth Skills Cameroon',
    popularity: 75,
    views: 780,
    registrations: 120,
    description: 'Career orientation, CV writing, scholarship guidance, and professional mentorship.',
  },
  {
    id: 5,
    title: 'Douala Food & Culture Fair',
    category: 'Food',
    city: 'Douala',
    region: 'Littoral',
    venue: 'Akwa Event Plaza',
    startDate: '2026-07-28T12:00:00',
    price: 2000,
    organizer: 'Taste Cameroon',
    popularity: 82,
    views: 1200,
    registrations: 350,
    description: 'Discover local dishes, traditional drinks, cultural dance, and family activities.',
  },
  {
    id: 6,
    title: 'Bamenda Cultural Heritage Festival',
    category: 'Culture',
    city: 'Bamenda',
    region: 'North-West',
    venue: 'Commercial Avenue',
    startDate: '2026-11-05T09:00:00',
    price: 3000,
    organizer: 'Heritage North-West',
    popularity: 79,
    views: 1050,
    registrations: 210,
    description: 'Traditional dances, exhibitions, storytelling, crafts, and cultural performances.',
  },
  {
    id: 7,
    title: 'Garoua Agribusiness Expo',
    category: 'Agriculture',
    city: 'Garoua',
    region: 'North',
    venue: 'Garoua Exhibition Centre',
    startDate: '2026-08-05T08:30:00',
    price: 0,
    organizer: 'AgriFuture CM',
    popularity: 71,
    views: 640,
    registrations: 160,
    description: 'Agricultural innovation, livestock, farm equipment, financing, and food processing.',
  },
  {
    id: 8,
    title: 'Yaoundé Health Awareness Day',
    category: 'Health',
    city: 'Yaoundé',
    region: 'Centre',
    venue: 'Palais des Sports',
    startDate: '2026-07-12T07:30:00',
    price: 0,
    organizer: 'Health For All Cameroon',
    popularity: 69,
    views: 900,
    registrations: 300,
    description: 'Free screening, public health talks, wellness coaching, and fitness sessions.',
  },
  {
    id: 9,
    title: 'Douala Comedy Night',
    category: 'Comedy',
    city: 'Douala',
    region: 'Littoral',
    venue: 'Canal Olympia Bessengue',
    startDate: '2026-07-18T20:00:00',
    price: 5000,
    organizer: 'Laugh237',
    popularity: 84,
    views: 1500,
    registrations: 500,
    description: 'Stand-up comedy show featuring popular comedians and new talents.',
  },
  {
    id: 10,
    title: 'Kribi Fashion Weekend',
    category: 'Fashion',
    city: 'Kribi',
    region: 'South',
    venue: 'Kribi Beach Resort',
    startDate: '2026-12-12T17:00:00',
    price: 15000,
    organizer: 'Fashion CM',
    popularity: 77,
    views: 990,
    registrations: 190,
    description: 'Runway shows, designers, beauty brands, networking, and creative fashion exhibitions.',
  },
]